# pyproject.toml
[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "ember"
version = "0.1.0"
description = "EMBER : Estimating Mass and Bolometric properties of Evolved Remnants"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
  "astropy", "astroquery", "lmfit", "tqdm", "corner",
  "pyvo", "gaiaxpy", "isochrones",
]

[tool.setuptools]
# package root is the repo root (not a 'src' layout)
package-dir = {"" = "."}

# discover the whole "catalog" package tree
[tool.setuptools.packages.find]
where = ["."]
include = ["catalog*"]

[tool.setuptools.package-data]
"catalog" = ["**/*.csv"]
